name: progressive_image_example
description: Flutter project to provide examples for the flutter progressive_image package.
publish_to: none
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  transparent_image: ^2.0.0
  google_fonts: ^4.0.0
  progressive_image:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.jpg
    - assets/images/placeholder.gif
